# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Eli.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 860)
        MainWindow.setStyleSheet("background-color:#478ac9;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(709, 30, 392, 236))
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("background-color:     #66CDAA;\n"
"font: 8pt \"Times New Roman\";\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC; ")
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.Tarix = QtWidgets.QTextEdit(self.centralwidget)
        self.Tarix.setGeometry(QtCore.QRect(466, 35, 148, 47))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Tarix.setFont(font)
        self.Tarix.setMouseTracking(False)
        self.Tarix.setStyleSheet("background-color:     #66CDAA;\n"
"font: 8pt \"Times New Roman\";\n"
"border-radius: 13px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.Tarix.setObjectName("Tarix")
        self.TB = QtWidgets.QToolButton(self.centralwidget)
        self.TB.setGeometry(QtCore.QRect(618, 35, 50, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TB.setFont(font)
        self.TB.setStyleSheet("background-color:#FFDAB9;\n"
"border-radius: 13px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.TB.setObjectName("TB")
        self.LCD1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD1.setGeometry(QtCore.QRect(469, 103, 50, 45))
        self.LCD1.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;")
        self.LCD1.setObjectName("LCD1")
        self.LCD2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD2.setGeometry(QtCore.QRect(530, 103, 50, 45))
        self.LCD2.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;")
        self.LCD2.setObjectName("LCD2")
        self.LCD3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD3.setGeometry(QtCore.QRect(589, 103, 74, 45))
        self.LCD3.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;")
        self.LCD3.setObjectName("LCD3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(240, 320, 901, 321))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color:#FFDAB9;\n"
"border-radius:17px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"\n"
"   \n"
"")
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setDragDropOverwriteMode(True)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        item.setFont(font)
        icon = QtGui.QIcon.fromTheme("red")
        item.setIcon(icon)
        item.setBackground(QtGui.QColor(240, 240, 240))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.PB1 = QtWidgets.QPushButton(self.centralwidget)
        self.PB1.setGeometry(QtCore.QRect(62, 333, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB1.setFont(font)
        self.PB1.setStyleSheet("background-color:#44c767;\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.PB1.setObjectName("PB1")
        self.PB3 = QtWidgets.QPushButton(self.centralwidget)
        self.PB3.setGeometry(QtCore.QRect(62, 411, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PB3.setFont(font)
        self.PB3.setStyleSheet("background-color:#44c767;\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.PB3.setObjectName("PB3")
        self.PB4 = QtWidgets.QPushButton(self.centralwidget)
        self.PB4.setGeometry(QtCore.QRect(62, 490, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB4.setFont(font)
        self.PB4.setStyleSheet("background-color:#44c767;\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.PB4.setObjectName("PB4")
        self.PB5 = QtWidgets.QPushButton(self.centralwidget)
        self.PB5.setGeometry(QtCore.QRect(63, 572, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB5.setFont(font)
        self.PB5.setStyleSheet("background-color:#44c767;\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;")
        self.PB5.setObjectName("PB5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 290, 101, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-left-radius: 8px;\n"
"text-align:center;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(498, 290, 111, 31))
        self.lineEdit_2.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(620, 290, 111, 31))
        self.lineEdit_3.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.PB6 = QtWidgets.QPushButton(self.centralwidget)
        self.PB6.setGeometry(QtCore.QRect(260, 650, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.PB6.setFont(font)
        self.PB6.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;\n"
"background-color:    #FFA500;")
        self.PB6.setObjectName("PB6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(780, 660, 101, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_4.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;\n"
"text-align:center;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(890, 660, 101, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;\n"
"text-align:center;")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(1000, 660, 101, 31))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_6.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-color: #0000CC;\n"
"border-radius: 8px;\n"
"text-align:center;")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(90, 60, 141, 61))
        self.textEdit.setStyleSheet("color:rgb(85, 0, 0);\n"
"background-color: rgb(255, 255, 127);\n"
"border-radius: 12px;\n"
"border:2px;\n"
"border-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tarix.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Tarixi Seçin:</span></p></body></html>"))
        self.TB.setText(_translate("MainWindow", "..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Malın adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Qiymət"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Miqdar"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Məbləğ"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ƏDV"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Ümumi Dəyər"))
        self.PB1.setText(_translate("MainWindow", "Add"))
        self.PB3.setText(_translate("MainWindow", "Delete"))
        self.PB4.setText(_translate("MainWindow", "Export Excel"))
        self.PB5.setText(_translate("MainWindow", "Export PDF"))
        self.PB6.setText(_translate("MainWindow", "YEKUN"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">Shop</span></p></body></html>"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
